//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stambul_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major_Roads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Major_Roads()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int id_Major_Roads { get; set; }
        public Nullable<int> Year_MR { get; set; }
        public byte[] Image_MR { get; set; }
        public System.Data.Entity.Spatial.DbGeography Scheme_MR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
