//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stambul_DB.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Growth
    {
        public int id_City_Growth { get; set; }
        public byte[] Diagram { get; set; }
        public byte[] Municipal_Border { get; set; }
        public Nullable<int> id_City_Maps { get; set; }
    
        public virtual City_Maps City_Maps { get; set; }
    }
}
