//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stambul_DB.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spaces_of_Everyday_Life
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spaces_of_Everyday_Life()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int Id_Spaces_of_Everyday_Life { get; set; }
        public System.Data.Entity.Spatial.DbGeography Beaches { get; set; }
        public System.Data.Entity.Spatial.DbGeography Casinos { get; set; }
        public System.Data.Entity.Spatial.DbGeography Spaces_of_Beyoglu { get; set; }
        public byte[] Image_SEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
