//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stambul_DB.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transportation()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int id_Transportation { get; set; }
        public Nullable<int> Year_T { get; set; }
        public string Name_T { get; set; }
        public byte[] Image_T { get; set; }
        public Nullable<int> id_Master_Plans { get; set; }
    
        public virtual Master_Plans Master_Plans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
